"""empty message

Revision ID: 11ca8a5eb462
Revises: f136a02828cf
Create Date: 2024-09-03 02:26:14.865045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11ca8a5eb462'
down_revision = 'f136a02828cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commenter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['commenter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('commenter_id')

    # ### end Alembic commands ###
